# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cK3Lcw18nmssYXxZdbV7P4WkmXafEz5b
"""

import io
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from google.colab import files
uploaded=files.upload()

data=pd.read_csv("Salary_Data.csv")
data.head()

m=data.iloc[:,:-1].values
n=data.iloc[:,1].values

from sklearn.model_selection import train_test_split
m_train,m_test,n_train,n_test=train_test_split(m,n,test_size=0.2,random_state=0)

from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(m_train,n_train)
n_pred=regressor.predict(m_test)
n_pred
n_test
plt.scatter(m_train,n_train,color='r')
plt.plot(m_train,regressor.predict(m_train),color='b')
plt.title("salary vs experience (tarining set)")

plt.xlabel("years of experience")
plt.ylabel("salaries")
plt.show()





